### ISSUE TITLE
[ReflectionException] Class Dutchento\Vatfallback\Model\VatNumber\Config\DataInterface does not exist

### ISSUE THREAD

**Issue by mkor** [Dutchento/m2-vatfallback#13]
Hi, Unfortunately, the module does not want to install on Magento 2.2.5 Open Source.

Tried to fix the errors I ran into as they occurred, but still stuck.

To fix this first error, 
in **Model/VatNumber/Config.php**, I replaced DataInterface with Data (because that one does exist)
```
namespace Dutchento\Vatfallback\Model\VatNumber;

use Dutchento\Vatfallback\Model\VatNumber\Config\Data;

class Config implements ConfigInterface
{
    /** @var Data  */
    private $dataSource;

    /**
     * Config constructor.
     * @param Data $dataSource
     */
    public function __construct(Data $dataSource)
    {
     	$this->dataSource = $dataSource;
    }

    /**
     * @inheritdoc
     */
    public function get(): array
    {
     	return $this->dataSource->get();
    }
}
```

next, in **Model/VatNumber/Config/Reader.php**, there is a bad reference:
`string $domDocumentClass = \Dom::class,`
I removed the backslash and added the following use:
`use Magento\Framework\Config\Dom;`

Next, we then run into an error on the include:
```
 [Magento\Framework\Config\Dom\ValidationSchemaException]
  Processed schema file: <M2_DIR>/vendor/dutchento/m2-vatfallback/etcvat_numbers.xsd
  Call to user entity loader callback '' has failedFailed to load external entity "NULL"
```
To fix this, I edited **Model/VatNumber/Config/SchemaLocator.php** on line 29 and added a path separator.

Finally, I run into the following error during setup:upgrade that I have as of yet been unable to fix.
```
[20-Dec-2018 10:11:22 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getNamedItem() on null in <M2_DIR>/vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php:51
Stack trace:
#0 <M2_DIR>/vendor/magento/framework/Config/Reader/Filesystem.php(171): Dutchento\Vatfallback\Model\VatNumber\Config\Converter->convert(Object(DOMDocument))
#1 <M2_DIR>/vendor/magento/framework/Config/Reader/Filesystem.php(130): Magento\Framework\Config\Reader\Filesystem->_readFiles(Object(Magento\Framework\Config\FileIterator))
#2 <M2_DIR>/vendor/magento/framework/Config/Data.php(104): Magento\Framework\Config\Reader\Filesystem->read()
#3 <M2_DIR>/vendor/magento/framework/Config/Data.php(92): Magento\Framework\Config\Data->initData()
#4 <M2_DIR>/vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Data.php in <M2_DIR>/vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php on line 51
```
Apparently, something now parses the XML file wrongly, so in stead of iterating over the multiple EU VAT regexes, it can only find a bad node containing only spaces and a newline.

**Comment by sandermangel** [comment]
Hi @mkor I took over your fixes in release 1.3.3.
For the XML parsing there was a new line in the regex XML which I removed, and I added a null check in the foreach to prevent it throwing errors in the future (will just be empty)
Please let me know if this fixed it

**Comment by mkor** [comment]
Hi Sander,
Probably not (It tried to iterate over empty values for a reason), but at
least we can now continue to the next issue:

Notice: Undefined variable: vatNumberNode in
<M2_ROOT>/vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php
on line 64

So I removed that, and next up we get:
```
[23-Dec-2018 13:22:04 UTC] PHP Fatal error:  Uncaught Error: Call to
undefined method
Dutchento\Vatfallback\Model\VatNumber\Config::getRegexMapping() in
<M2_ROOT>/vendor/dutchento/m2-vatfallback/Service/Validate/Regex.php:28
Stack trace:
#0
<M2_ROOT>/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111):
Dutchento\Vatfallback\Service\Validate\Regex->__construct(Object(Dutchento\Vatfallback\Model\VatNumber\Config))
#1
<M2_ROOT>/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66):
Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Dutchento\\Vatfa...',
Array)
#2  <M2_ROOT>/vendor/magento/framework/ObjectManager/ObjectManager.php(70):
Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Dutchento\\Vatfa...')
#3
<M2_ROOT>/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(14
in /home/deonet/domains/
deonet.com/public_html/clone/vendor/dutchento/m2-vatfallback/Service/Validate/Regex.php
on line 28
```
(yeah, that would probably be the rename in
commit 3dd2af8f2d50ba3d1cb5831f23edb9830015c5df)

**Comment by jissereitsma** [comment]
PR: https://github.com/Dutchento/m2-vatfallback/pull/16

**Comment by mkor** [comment]
This issue appears fixed with the latest commit :)
