### ISSUE TITLE
Undefined variable $vatNumberNode

### ISSUE THREAD

**Issue by jissereitsma** [Dutchento/m2-vatfallback#15]
The following line is completely broken, referencing a variable object that does not exist: https://github.com/Dutchento/m2-vatfallback/blob/98b5392e62c73277db9e78994f728f357d1494a6/Model/VatNumber/Config/Converter.php#L64

From this, I can deduct that the entire method `stripAndValidatePattern` does not work, which again leads to the method `convert` of the same class does not work, which leads to the conclusion that the entire class is not used either. This class is used again as a dep of `Reader` in the same directory. 

Before starting to fix a bubble, does anyone now what went wrong here?

**Comment by jissereitsma** [comment]
Specifically @sandermangel because it is his commit. https://github.com/Dutchento/m2-vatfallback/commit/e7205cb444a78260badd0ae72d8db7afef4d7d08#diff-a3a859c44fcd5fafb6804ab9e283d48e

**Comment by jissereitsma** [comment]
Different Issue but it also mentions the same: https://github.com/Dutchento/m2-vatfallback/issues/13

**Comment by jissereitsma** [comment]
See also PR: https://github.com/Dutchento/m2-vatfallback/pull/16

**Comment by JeroenBoersma** [comment]
this is already fixed, because the MR is merged :)
