### ISSUE TITLE
VAT codes fail to validate correctly - VIES + RegExp

### ISSUE THREAD

**Issue by mkor** [Dutchento/m2-vatfallback#25]
I have a couple of dutch VAT codes that fail to verify correctly.
Do you also have this issue?

I currently have enabled:
- VIES and Regular Expressions
- VatLayer is disabled

Unfortunately I don't have time atm to properly verify things, but I suspect you did not fix the VIES response parser since 1.3, that I proposed?
If you did not, then the unofficial VIES Validation step is broken and cannot return VALID.

**Comment by peterjaap** [comment]
We used to be able to check it manually, but it seems they removed it? https://ec.europa.eu/taxation_customs/vies/?locale=nl

So can't be sure at this point.
