### ISSUE TITLE
"request_message" type in the response object is not consistent

### ISSUE THREAD

**Issue by Serializator** [Dutchento/m2-vatfallback#36]
I today ran into some odd behaviour in regards to the response object from `Magento\Customer\Model\Vat::checkVatNumber`, this seem to be caused by the `Dutchento\Vatfallback\Plugin\Magento\Customer\Model\Vat` plugin.

In the original data object the `request_message` is returned as a `Magento\Framework\Phrase`, but as soon as the aforementioned plugin interferes with this data object, it becomes a string.

When using static return types this is an issue. I want to use a single return type for a method, but need to return `string|Magento\Framework\Phrase` through the PHPDoc to support this behaviour. Or I need to check whether it is a string and create a `Magento\Framework\Phrase` from it, or vice-versa.

**Steps to Reproduce**
- Put a breakpoint in `Dutchento\Vatfallback\Plugin\Magento\Customer\Model\Vat` after `$gatewayResponse` is assigned
- Take not of the type of the `request_message` property within the data object (which is a `Magento\Framework\Phrase`)
- Put a breakpoint at the start of `Dutchento\Vatfallback\Plugin\Magento\Customer\Model\Vat::createGatewayResponseObject`
- Take note of the type of the `$message` argument (which is now a string, and will make `request_message` be a string)

**Comment by peterjaap** [comment]
@Serializator what would be your preferred solution?

**Comment by Serializator** [comment]
@peterjaap, I suppose that the type stays consistent, thus stay of type `Magento\Framework\Phrase` rather than becoming a `string` somewhere in a plugin.

**Comment by peterjaap** [comment]
@Serializator I think this should do it? https://github.com/Dutchento/m2-vatfallback/pull/37

**Comment by Serializator** [comment]
Hi @peterjaap, thank you for the quick help! I haven't yet tried the update but I suspect this will do you the job. Thank you!
