### ISSUE TITLE
No validation took place

### ISSUE THREAD

**Issue by dearste** [Dutchento/m2-vatfallback#38]
Hi, I get always No validation took place. Where is my issue?
Also with your example bin/magento vat:validate NL NL133001477B01

**Comment by JustinElst** [comment]
Little late to the party, but anyway, here we go:
Did you check the configuration?
- https://github.com/Dutchento/m2-vatfallback/issues/42 talks about the unofficial vies check being broken, disable this
- If Magento core vies check failed (which is quite frequently) and the other services are not configured correctly you will get this message
- If vatlayer is configured but has reached its request limit it fails

**Comment by peterjaap** [comment]
This problem might now be solved in the latest release; https://github.com/Dutchento/m2-vatfallback/releases/tag/2.0.0

Please re-open if not.
