### ISSUE TITLE
Call to viesquer.do results in 404

### ISSUE THREAD

**Issue by evs-xsarus** [Dutchento/m2-vatfallback#42]
Seems like http://ec.europa.eu/taxation_customs/vies/viesquer.do does not exist anymore. If you go to 

https://ec.europa.eu/taxation_customs/vies/#/vat-validation

A form can be seen which will post to  

https://ec.europa.eu/taxation_customs/vies/rest-api/ms/<countrycode>/vat/<vatnumber>?requesterMemberStateCode=<countrycode>&requesterNumber=<vatnumber>

Could you check if the module must be updated for this.

**Comment by peterjaap** [comment]
Looks like other packages are querying the WSDL: https://github.com/DragonBe/vies/blob/c7a1c44f8c451bba14b19ac350ebf12813fce198/src/Vies/Vies.php#L52

**Comment by JustinElst** [comment]
I think, that https://github.com/Dutchento/m2-vatfallback/pull/43 fixes this. But at the same time that PR removes using the Magento core Vies request.

**Comment by peterjaap** [comment]
We have merged #43 so this is now fixed. 

https://github.com/Dutchento/m2-vatfallback/releases/tag/2.0.0
