### ISSUE TITLE
Error after upgrade m2-vatfallback

### ISSUE THREAD

**Issue by SolsWebdesign** [Dutchento/m2-vatfallback#45]
Upgrading a shop from 2.4.3 to 2.4.4 (yes, I know it is late) and m2_vatfallback from 1.6.4 to ^2.0 I get the following error:
unexpected ')', expecting variable (T_VARIABLE) upon setup:upgrade.

Since I've seen the error before I just had to find out in what extension (added an echo to composer...ClassLoader) and found your great module. So what is the issue?

In Dutchento\Vatfallback\Service\Validate\Vies it is the contruct:
```
public function __construct(
        ConfigurationInterface $configuration,
        Client                 $client, <------------------------ has a comma
    ) {
        $this->configuration = $configuration;
        $this->client        = $client;
    }
```

Not sure why Composer makes such a big deal of it but there you go.
Next up is Dutchento\Vatfallback\Service\Vies\Client with the following construct:

```
public function getViesResponse(
        string $countryIso,
        string $vatNumber,
        int    $timeout = 1,   <------------- has a comma
    ): mixed {
```
I guess there may have been a line below both comma's and the comma's were just left behind...

Thanks though, for this great module, it is a total live saver :-)

**Comment by peterjaap** [comment]
@SolsWebdesign That's weird, PHP allows trailing comma's since version 7.2. Seeing as PHP 7.4 is the minimum for Magento 2.4.3, this shouldn't be a problem..

**Comment by SolsWebdesign** [comment]
@peterjaap you are right! I checked the docs and it should not be a problem. Not sure what caused it but for now I will close this issue. If it happens again I will add the info to this closed info :-)
